# mysql
mysqlcontainer:
  build: ./dockerfiles/mysql
  ports:
    - "3306:3306"
  volumes:
    - ./app/dbfile:/var/lib/mysql

# php
phpcontainer:
  build: ./dockerfiles/php
  ports:
    - "9000"
  volumes:
    - ./configs/php/php.ini:/usr/local/etc/php/php.ini:ro
    - ./app/website:/usr/share/nginx/html
  links:
    - mysqlcontainer

# nginx
nginxcontainer:
  build: ./dockerfiles/nginx
  ports:
    - "80:80"
  volumes:
    - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./configs/conf.d:/etc/nginx/conf.d:ro
    - ./app/log/nginxlog:/var/log/nginx
    - ./app/website:/usr/share/nginx/html
  links:
    - phpcontainer
